server:
  port: 9090

kafka :
  bootstrap-servers: localhost:9092
  group-id: consumer
  topic: test
  error-topic: error
  topic-polling: 1000 # interval of consumer.poll in MessageConsumer
  consumers-count: 5 # number of consumer threads to spin
  processor-thread-pool: 100 # the max thread pool size for threads processing each record
  max-poll-records: 10 # the max number of records kafka-consumer can read in a poll
  max-poll-interval: 60000 # the max time between poll intervals allowed
  monitor-polling: 1000 # the interval to verify number of consumer threads
  session-timeout: 30000
  request-timeout: 120000

addValue:
  url: http://localhost:1234/message/add
  readTimeout: 1500
  connectTimeout: 500
  clientConnectionManager:
    defaultMaxPerRoute: 200
    maxTotal: 400

recoverable-retry:
  min: 3000

hystrix:
  threadpool:
    default: 50
  timeout:
    default: 1500
    # switch the value < or > 3000 would change the behavior
    AddValueCommand: 5000
    DWWriteCommand: 3000